#!/bin/bash
#
# brew-backup generates Brewfile that will hopefully install the same
# software (WARNING: options won't be kept)
#

taps=$(brew tap)
for tap in $taps; do
  echo tap $tap
done
echo ""
formulas="$(brew list -1)"
for f in $formulas; do
  # try default
  if brew info $f &> /dev/null; then
    echo install $f
    continue;
  fi

  # go over taps one by one
  for tap in $taps; do
    if brew info $tap/$f &>/dev/null; then
      echo install $tap/$f
      break
    fi
  done
done
