tap homebrew/dupes

install bash
install binutils  --default-names
install ccache
install cmake
install coreutils --default-names
install curl
install diffutils --default-names
install emacs
install file-formula
install findutils --default-names
install gawk
install gibo
install git
install gnu-indent --default-names
install gnu-sed --default-names
install gnu-tar --default-names
install gnu-which --default-names
install gnutls --default-names
install go
install gpatch
install grep --default-names
install gzip
install hub
install imagemagick
install m4
install make
install mc
install nano
install npm
install openssh --with-brewed-openssl
install python
install rsync
install screen
install ssh-copy-id
install svn
install tig
install tree
install unzip
install vim --override-system-vi
install watch
install wdiff --with-gettext
install wget
install zsh
install graphviz
install ninja
install doxygen
install htop
install homebrew/completions/vagrant-completion
install android-sdk
install android-ndk
install mutt
install gti
install sl
